version: '3.8'

services:

  selenium-hub:
    image: selenium/hub:4.21.0
    ports:
      - "4444:4444"

  chrome-node-1:
    image: selenium/node-chrome:4.21.0
    depends_on:
      - selenium-hub

  chrome-node-2:
    image: selenium/node-chrome:4.21.0
    depends_on:
      - selenium-hub

  chrome-node-3:
    image: selenium/node-chrome:4.21.0
    depends_on:
      - selenium-hub